name: Docker Image CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        permissions:
            packages: write # Required to push images to ghcr.io
            contents: read

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to GitHub Container Registry
              if: github.event_name == 'push'
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Docker meta
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ghcr.io/${{ github.repository_owner }}/bino
                  tags: |
                      type=raw,value=latest,enable=${{ github.event_name == 'push' }}
                      type=sha,prefix=sha-
                      type=sha,format=short
                      type=ref,event=branch
                      type=ref,event=pr
                      type=schedule,pattern={{date 'YYYYMMDD'}}

            - name: Build and Push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: ${{ github.event_name == 'push' }}
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
                  cache-from: |
                      type=gha,scope=${{ github.ref_name == 'main' && 'main' || '' }}
                      type=registry,ref=ghcr.io/${{ github.repository_owner }}/bino:latest
                  cache-to: ${{ github.ref_name == 'main' && 'type=gha,mode=max' || '' }}
